name: twitter_client
description: A Twitter Client library cross platform support and easy to use.
version: 0.0.6
homepage: https://youtube.com/@azkadev
repository: https://github.com/azkadev

environment:
  sdk: '>=2.19.0 <4.0.0'

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  lints: ^2.1.0
  test: ^1.24.2
dependencies:
  galaxeus_lib: ^0.0.64
  twitter_api_v2: ^4.9.4
  universal_io: ^2.2.0
